package com.vanloi.model;
// Generated Mar 2, 2017 3:07:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enrollment generated by hbm2java
 */
@Entity
@Table(name = "enrollment")
public class Enrollment{

	private Integer enrollId;
	private Student student;
	private Subject subject;
	private Date enrollTime;

	public Enrollment() {
	}

	public Enrollment(Student student, Subject subject, Date enrollTime) {
		this.student = student;
		this.subject = subject;
		this.enrollTime = enrollTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "enroll_id", unique = true, nullable = false)
	public Integer getEnrollId() {
		return this.enrollId;
	}

	public void setEnrollId(Integer enrollId) {
		this.enrollId = enrollId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enroll_time", length = 10)
	public Date getEnrollTime() {
		return this.enrollTime;
	}

	public void setEnrollTime(Date enrollTime) {
		this.enrollTime = enrollTime;
	}

}
