package com.vanloi.model;
// Generated Mar 2, 2017 2:31:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;

import org.hibernate.validator.constraints.Range;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * StudentInfo generated by hbm2java
 */
@Entity
@Table(name = "student_info")
public class StudentInfo{

	private Integer infoId;
	private Student student;
	
	private String address;
	@NotNull
	@DecimalMax("10.0") 
	@DecimalMin("0.0") 
	private double averageScore;
	@Past
	private Date dateOfBirth;

	public StudentInfo() {
	}

	public StudentInfo(double averageScore) {
		this.averageScore = averageScore;
	}

	public StudentInfo(Student student, String address, double averageScore, Date dateOfBirth) {
		this.student = student;
		this.address = address;
		this.averageScore = averageScore;
		this.dateOfBirth = dateOfBirth;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "info_id", unique = true, nullable = false)
	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	@ManyToOne
    @JoinColumn(name = "student_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "average_score", nullable = false, precision = 22, scale = 0)
	public double getAverageScore() {
		return this.averageScore;
	}

	public void setAverageScore(double averageScore) {
		this.averageScore = averageScore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", length = 10)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

}
